apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksctl-pingpong
  region: eu-central-1

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 2
    volumeSize: 80
    ssh:
      allow: false
  - name: ng-2
    instanceType: t2.micro
    desiredCapacity: 2
    volumeSize: 100
    ssh:
      allow: false