apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-app
  namespace: pingpong-namespace
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: pingpong-app
  template:
    metadata:
      labels:
        app: pingpong-app
    spec:
      containers:
        - name: pingpong-app
          image: 630357415186.dkr.ecr.eu-central-1.amazonaws.com/pingpong-repo:pingpong-tag
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080