apiVersion: v1
kind: Service
metadata:
  name: pingpong-service
  namespace: pingpong-namespace
spec:
  selector:
    app: pingpong-app
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer